"""schema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-07-09 23:48:11.394422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('chave', name=op.f('pk_application_settings'))
    )
    op.create_table('duplicate_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Enum('EXATO', 'CONTEUDO', 'VISUAL', name='duplicatelevel', native_enum=False), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_groups'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('metodo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('regiao', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('fonte', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('cache_key', name=op.f('uq_locations_cache_key'))
    )
    op.create_table('operation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PLANEJADA', 'APROVADA', 'EXECUTANDO', 'CONCLUIDA', 'CANCELADA', 'ERRO', name='operationstatus', native_enum=False), nullable=False),
    sa.Column('dry_run_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_plans'))
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('relacao', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.Text(), nullable=False),
    sa.Column('apelido', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('padroes_ignorados', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('caminho', name=op.f('uq_sources_caminho'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('nome', name=op.f('uq_tags_nome'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quando', sa.DateTime(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('detalhe', sa.JSON(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['operation_plans.id'], name=op.f('fk_audit_log_plan_id_operation_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('blob_criptografado', sa.LargeBinary(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_face_embeddings_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_embeddings'))
    )
    op.create_table('scan_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RODANDO', 'PAUSADO', 'CONCLUIDO', 'ERRO', name='scanstatus', native_enum=False), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.Column('checkpoint', sa.JSON(), nullable=True),
    sa.Column('arquivos_vistos', sa.Integer(), nullable=False),
    sa.Column('arquivos_indexados', sa.Integer(), nullable=False),
    sa.Column('erros', sa.Integer(), nullable=False),
    sa.Column('bytes_processados', sa.Integer(), nullable=False),
    sa.Column('versao_scanner', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_scan_sessions_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_sessions'))
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('metodo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_trips_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.Text(), nullable=False),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('pasta', sa.Text(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('extensao', sa.String(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('inode', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.Column('data_capturada', sa.DateTime(), nullable=True),
    sa.Column('tz_estimado', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('lente', sa.String(), nullable=True),
    sa.Column('orientacao', sa.Integer(), nullable=True),
    sa.Column('largura', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('hash_rapido', sa.String(), nullable=True),
    sa.Column('hash_sha256', sa.String(), nullable=True),
    sa.Column('status_revisao', sa.Enum('NAO_REVISADO', 'PENDENTE', 'REVISADO', name='reviewstatus', native_enum=False), nullable=False),
    sa.Column('erro_leitura', sa.Text(), nullable=True),
    sa.Column('indexado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_media_files_event_id_events')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_media_files_location_id_locations')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_media_files_source_id_sources')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_media_files_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files')),
    sa.UniqueConstraint('source_id', 'caminho', name=op.f('uq_media_files_source_id'))
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index('ix_media_files_data_capturada', ['data_capturada'], unique=False)
        batch_op.create_index('ix_media_files_hash_rapido', ['hash_rapido'], unique=False)
        batch_op.create_index('ix_media_files_mtime_tamanho', ['mtime', 'tamanho'], unique=False)

    op.create_table('duplicate_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.Enum('INDEFINIDO', 'PRINCIPAL', 'VERSAO', 'IGNORADO', name='duplicaterole', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['duplicate_groups.id'], name=op.f('fk_duplicate_members_group_id_duplicate_groups')),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_duplicate_members_media_id_media_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_members')),
    sa.UniqueConstraint('group_id', 'media_id', name=op.f('uq_duplicate_members_group_id'))
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('nivel', sa.Enum('ALTA', 'MEDIA', 'BAIXA', name='confidencelevel', native_enum=False), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('versao_logica', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_evidence_media_id_media_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_media_id', ['media_id'], unique=False)

    op.create_table('face_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('estado', sa.Enum('DETECTADO', 'POSSIVEL', 'CONFIRMADO', 'INCORRETO', name='facestate', native_enum=False), nullable=False),
    sa.Column('similaridade', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_face_occurrences_media_id_media_files')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_face_occurrences_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_occurrences'))
    )
    op.create_table('media_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_media_tags_media_id_media_files')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_media_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_tags')),
    sa.UniqueConstraint('media_id', 'tag_id', name=op.f('uq_media_tags_media_id'))
    )
    op.create_table('metadata_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_metadata_entries_media_id_media_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata_entries'))
    )
    with op.batch_alter_table('metadata_entries', schema=None) as batch_op:
        batch_op.create_index('ix_metadata_entries_media_id', ['media_id'], unique=False)

    op.create_table('operation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('operacao', sa.Enum('COPIAR', name='operationtype', native_enum=False), nullable=False),
    sa.Column('origem', sa.Text(), nullable=False),
    sa.Column('destino', sa.Text(), nullable=False),
    sa.Column('conflito', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANEJADA', 'APROVADA', 'EXECUTANDO', 'CONCLUIDA', 'CANCELADA', 'ERRO', name='operationstatus', native_enum=False), nullable=False),
    sa.Column('hash_pre', sa.String(), nullable=True),
    sa.Column('hash_pos', sa.String(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_operation_items_media_id_media_files')),
    sa.ForeignKeyConstraint(['plan_id'], ['operation_plans.id'], name=op.f('fk_operation_items_plan_id_operation_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_items'))
    )
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('destino_sugerido', sa.Text(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('nivel', sa.Enum('ALTA', 'MEDIA', 'BAIXA', name='confidencelevel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADA', 'REJEITADA', 'EDITADA', name='suggestionstatus', native_enum=False), nullable=False),
    sa.Column('versao_logica', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('revisado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_suggestions_media_id_media_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestions'))
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index('ix_suggestions_status', ['status'], unique=False)

    op.create_table('suggestion_evidence',
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_suggestion_evidence_evidence_id_evidence')),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], name=op.f('fk_suggestion_evidence_suggestion_id_suggestions')),
    sa.PrimaryKeyConstraint('suggestion_id', 'evidence_id', name=op.f('pk_suggestion_evidence'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion_evidence')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index('ix_suggestions_status')

    op.drop_table('suggestions')
    op.drop_table('operation_items')
    with op.batch_alter_table('metadata_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_metadata_entries_media_id')

    op.drop_table('metadata_entries')
    op.drop_table('media_tags')
    op.drop_table('face_occurrences')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_media_id')

    op.drop_table('evidence')
    op.drop_table('duplicate_members')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index('ix_media_files_mtime_tamanho')
        batch_op.drop_index('ix_media_files_hash_rapido')
        batch_op.drop_index('ix_media_files_data_capturada')

    op.drop_table('media_files')
    op.drop_table('trips')
    op.drop_table('scan_sessions')
    op.drop_table('face_embeddings')
    op.drop_table('audit_log')
    op.drop_table('tags')
    op.drop_table('sources')
    op.drop_table('people')
    op.drop_table('operation_plans')
    op.drop_table('locations')
    op.drop_table('events')
    op.drop_table('duplicate_groups')
    op.drop_table('application_settings')
    # ### end Alembic commands ###
