"""Fuso IANA representativo por país, na mesma grafia que `paises.py` produz.

`tz_estimado` (D-038) precisa de um fuso por país, não de geometria
coordenada→fuso: a granularidade é grosseira de propósito, no mesmo nível
que o resto do app já assume para país estimado (GPS próprio, herança
temporal de D-025, ou nome de pasta). Sem dependência nova
(`timezonefinder`/`pytz`/`geo-tz` descartados, D-07) e sem rede, como manda
o invariante 4 — tabela estática, no mesmo espírito de `paises.py`.

A chave é o nome em português que `PAISES_PT` produz (não o código ISO):
o valor de `Evidence.valor` já chega como nome, e recodificar de volta
para ISO só para procurar aqui seria trabalho e fonte de bug a mais.

Regra de preenchimento (D-08), documentada uma vez:

- País com um único fuso oficial: identificador IANA canônico da capital
  (França → "Europe/Paris", Japão → "Asia/Tokyo").
- País com mais de um fuso oficial: fuso da capital ou o de maior
  população — aproximação deliberada, não um substituto de
  `timezonefinder`. Brasil → "America/Sao_Paulo" (capital Brasília, mesmo
  fuso de São Paulo/Rio); Estados Unidos → "America/New_York" (capital
  Washington DC, fuso Eastern, também o mais populoso); Rússia →
  "Europe/Moscow"; Canadá → "America/Toronto" (capital Ottawa, fuso
  Eastern — IANA não tem "America/Ottawa"); Austrália → "Australia/Sydney"
  (região da capital Canberra, também a mais populosa). Mesma regra
  aplicada aos demais países multi-fuso da tabela (ex.: México, Indonésia,
  Portugal, Espanha, Chile, Equador, Cazaquistão, Mongólia, Micronésia).
- Território sem população permanente (Ilha Bouvet, Ilha Heard e Ilhas
  McDonald): sem capital nem habitante para decidir por população, o
  critério acima não se aplica. Usa-se o fuso fixo mais próximo pela
  longitude real do território — "Etc/GMT" para a Ilha Bouvet (~3°E,
  perto do meridiano de Greenwich), "Indian/Kerguelen" para Heard/McDonald
  (mesma região do Índico Sul que o território francês vizinho, já
  presente nesta tabela).
- Território sem identificador IANA próprio (Kosovo): usa-se o fuso do
  território com quem compartilha as mesmas regras de horário —
  "Europe/Belgrade" (Sérvia).
- "Antártida" (código ISO genérico AQ, sem país real por trás): não há
  fuso único correto — usa-se "Antarctica/McMurdo" (base americana,
  horário da Nova Zelândia) como referência estável, mesma lógica de
  aproximação deliberada dos demais casos acima.

Todo valor é validado em teste contra `zoneinfo.available_timezones()`
(stdlib, sem dependência nova) — rede de segurança contra erro de
digitação num identificador que só vai doer quando alguém tentar
convertê-lo.
"""

from __future__ import annotations

# Nome em português (mesma grafia de PAISES_PT.values()) → identificador
# IANA. Ordem espelha a ordem de PAISES_PT (por código ISO alfa-2), para
# facilitar comparação lado a lado durante revisão.
TZ_POR_PAIS: dict[str, str] = {
    "Andorra": "Europe/Andorra",
    "Emirados Árabes Unidos": "Asia/Dubai",
    "Afeganistão": "Asia/Kabul",
    "Antígua e Barbuda": "America/Antigua",
    "Anguilla": "America/Anguilla",
    "Albânia": "Europe/Tirane",
    "Armênia": "Asia/Yerevan",
    "Angola": "Africa/Luanda",
    "Antártida": "Antarctica/McMurdo",
    "Argentina": "America/Argentina/Buenos_Aires",
    "Samoa Americana": "Pacific/Pago_Pago",
    "Áustria": "Europe/Vienna",
    "Austrália": "Australia/Sydney",
    "Aruba": "America/Aruba",
    "Ilhas Åland": "Europe/Mariehamn",
    "Azerbaijão": "Asia/Baku",
    "Bósnia e Herzegovina": "Europe/Sarajevo",
    "Barbados": "America/Barbados",
    "Bangladesh": "Asia/Dhaka",
    "Bélgica": "Europe/Brussels",
    "Burkina Faso": "Africa/Ouagadougou",
    "Bulgária": "Europe/Sofia",
    "Bahrein": "Asia/Bahrain",
    "Burundi": "Africa/Bujumbura",
    "Benin": "Africa/Porto-Novo",
    "São Bartolomeu": "America/St_Barthelemy",
    "Bermudas": "Atlantic/Bermuda",
    "Brunei": "Asia/Brunei",
    "Bolívia": "America/La_Paz",
    "Países Baixos Caribenhos": "America/Kralendijk",
    "Brasil": "America/Sao_Paulo",
    "Bahamas": "America/Nassau",
    "Butão": "Asia/Thimphu",
    "Ilha Bouvet": "Etc/GMT",
    "Botsuana": "Africa/Gaborone",
    "Belarus": "Europe/Minsk",
    "Belize": "America/Belize",
    "Canadá": "America/Toronto",
    "Ilhas Cocos": "Indian/Cocos",
    "República Democrática do Congo": "Africa/Kinshasa",
    "República Centro-Africana": "Africa/Bangui",
    "República do Congo": "Africa/Brazzaville",
    "Suíça": "Europe/Zurich",
    "Costa do Marfim": "Africa/Abidjan",
    "Ilhas Cook": "Pacific/Rarotonga",
    "Chile": "America/Santiago",
    "Camarões": "Africa/Douala",
    "China": "Asia/Shanghai",
    "Colômbia": "America/Bogota",
    "Costa Rica": "America/Costa_Rica",
    "Cuba": "America/Havana",
    "Cabo Verde": "Atlantic/Cape_Verde",
    "Curaçao": "America/Curacao",
    "Ilha Christmas": "Indian/Christmas",
    "Chipre": "Asia/Nicosia",
    "Tchéquia": "Europe/Prague",
    "Alemanha": "Europe/Berlin",
    "Djibuti": "Africa/Djibouti",
    "Dinamarca": "Europe/Copenhagen",
    "Dominica": "America/Dominica",
    "República Dominicana": "America/Santo_Domingo",
    "Argélia": "Africa/Algiers",
    "Equador": "America/Guayaquil",
    "Estônia": "Europe/Tallinn",
    "Egito": "Africa/Cairo",
    "Saara Ocidental": "Africa/El_Aaiun",
    "Eritreia": "Africa/Asmara",
    "Espanha": "Europe/Madrid",
    "Etiópia": "Africa/Addis_Ababa",
    "Finlândia": "Europe/Helsinki",
    "Fiji": "Pacific/Fiji",
    "Ilhas Malvinas": "Atlantic/Stanley",
    "Micronésia": "Pacific/Pohnpei",
    "Ilhas Faroe": "Atlantic/Faroe",
    "França": "Europe/Paris",
    "Gabão": "Africa/Libreville",
    "Reino Unido": "Europe/London",
    "Granada": "America/Grenada",
    "Geórgia": "Asia/Tbilisi",
    "Guiana Francesa": "America/Cayenne",
    "Guernsey": "Europe/Guernsey",
    "Gana": "Africa/Accra",
    "Gibraltar": "Europe/Gibraltar",
    "Groenlândia": "America/Nuuk",
    "Gâmbia": "Africa/Banjul",
    "Guiné": "Africa/Conakry",
    "Guadalupe": "America/Guadeloupe",
    "Guiné Equatorial": "Africa/Malabo",
    "Grécia": "Europe/Athens",
    "Geórgia do Sul e Sandwich do Sul": "Atlantic/South_Georgia",
    "Guatemala": "America/Guatemala",
    "Guam": "Pacific/Guam",
    "Guiné-Bissau": "Africa/Bissau",
    "Guiana": "America/Guyana",
    "Hong Kong": "Asia/Hong_Kong",
    "Ilha Heard e Ilhas McDonald": "Indian/Kerguelen",
    "Honduras": "America/Tegucigalpa",
    "Croácia": "Europe/Zagreb",
    "Haiti": "America/Port-au-Prince",
    "Hungria": "Europe/Budapest",
    "Indonésia": "Asia/Jakarta",
    "Irlanda": "Europe/Dublin",
    "Israel": "Asia/Jerusalem",
    "Ilha de Man": "Europe/Isle_of_Man",
    "Índia": "Asia/Kolkata",
    "Território Britânico do Oceano Índico": "Indian/Chagos",
    "Iraque": "Asia/Baghdad",
    "Irã": "Asia/Tehran",
    "Islândia": "Atlantic/Reykjavik",
    "Itália": "Europe/Rome",
    "Jersey": "Europe/Jersey",
    "Jamaica": "America/Jamaica",
    "Jordânia": "Asia/Amman",
    "Japão": "Asia/Tokyo",
    "Quênia": "Africa/Nairobi",
    "Quirguistão": "Asia/Bishkek",
    "Camboja": "Asia/Phnom_Penh",
    "Kiribati": "Pacific/Tarawa",
    "Comores": "Indian/Comoro",
    "São Cristóvão e Névis": "America/St_Kitts",
    "Coreia do Norte": "Asia/Pyongyang",
    "Coreia do Sul": "Asia/Seoul",
    "Kuwait": "Asia/Kuwait",
    "Ilhas Cayman": "America/Cayman",
    "Cazaquistão": "Asia/Almaty",
    "Laos": "Asia/Vientiane",
    "Líbano": "Asia/Beirut",
    "Santa Lúcia": "America/St_Lucia",
    "Liechtenstein": "Europe/Vaduz",
    "Sri Lanka": "Asia/Colombo",
    "Libéria": "Africa/Monrovia",
    "Lesoto": "Africa/Maseru",
    "Lituânia": "Europe/Vilnius",
    "Luxemburgo": "Europe/Luxembourg",
    "Letônia": "Europe/Riga",
    "Líbia": "Africa/Tripoli",
    "Marrocos": "Africa/Casablanca",
    "Mônaco": "Europe/Monaco",
    "Moldávia": "Europe/Chisinau",
    "Montenegro": "Europe/Podgorica",
    "São Martinho": "America/Marigot",
    "Madagascar": "Indian/Antananarivo",
    "Ilhas Marshall": "Pacific/Majuro",
    "Macedônia do Norte": "Europe/Skopje",
    "Mali": "Africa/Bamako",
    "Mianmar": "Asia/Yangon",
    "Mongólia": "Asia/Ulaanbaatar",
    "Macau": "Asia/Macau",
    "Ilhas Marianas do Norte": "Pacific/Saipan",
    "Martinica": "America/Martinique",
    "Mauritânia": "Africa/Nouakchott",
    "Montserrat": "America/Montserrat",
    "Malta": "Europe/Malta",
    "Maurício": "Indian/Mauritius",
    "Maldivas": "Indian/Maldives",
    "Malaui": "Africa/Blantyre",
    "México": "America/Mexico_City",
    "Malásia": "Asia/Kuala_Lumpur",
    "Moçambique": "Africa/Maputo",
    "Namíbia": "Africa/Windhoek",
    "Nova Caledônia": "Pacific/Noumea",
    "Níger": "Africa/Niamey",
    "Ilha Norfolk": "Pacific/Norfolk",
    "Nigéria": "Africa/Lagos",
    "Nicarágua": "America/Managua",
    "Países Baixos": "Europe/Amsterdam",
    "Noruega": "Europe/Oslo",
    "Nepal": "Asia/Kathmandu",
    "Nauru": "Pacific/Nauru",
    "Niue": "Pacific/Niue",
    "Nova Zelândia": "Pacific/Auckland",
    "Omã": "Asia/Muscat",
    "Panamá": "America/Panama",
    "Peru": "America/Lima",
    "Polinésia Francesa": "Pacific/Tahiti",
    "Papua-Nova Guiné": "Pacific/Port_Moresby",
    "Filipinas": "Asia/Manila",
    "Paquistão": "Asia/Karachi",
    "Polônia": "Europe/Warsaw",
    "São Pedro e Miquelão": "America/Miquelon",
    "Ilhas Pitcairn": "Pacific/Pitcairn",
    "Porto Rico": "America/Puerto_Rico",
    "Palestina": "Asia/Gaza",
    "Portugal": "Europe/Lisbon",
    "Palau": "Pacific/Palau",
    "Paraguai": "America/Asuncion",
    "Catar": "Asia/Qatar",
    "Reunião": "Indian/Reunion",
    "Romênia": "Europe/Bucharest",
    "Sérvia": "Europe/Belgrade",
    "Rússia": "Europe/Moscow",
    "Ruanda": "Africa/Kigali",
    "Arábia Saudita": "Asia/Riyadh",
    "Ilhas Salomão": "Pacific/Guadalcanal",
    "Seicheles": "Indian/Mahe",
    "Sudão": "Africa/Khartoum",
    "Suécia": "Europe/Stockholm",
    "Singapura": "Asia/Singapore",
    "Santa Helena": "Atlantic/St_Helena",
    "Eslovênia": "Europe/Ljubljana",
    "Svalbard e Jan Mayen": "Arctic/Longyearbyen",
    "Eslováquia": "Europe/Bratislava",
    "Serra Leoa": "Africa/Freetown",
    "San Marino": "Europe/San_Marino",
    "Senegal": "Africa/Dakar",
    "Somália": "Africa/Mogadishu",
    "Suriname": "America/Paramaribo",
    "Sudão do Sul": "Africa/Juba",
    "São Tomé e Príncipe": "Africa/Sao_Tome",
    "El Salvador": "America/El_Salvador",
    "Sint Maarten": "America/Lower_Princes",
    "Síria": "Asia/Damascus",
    "Essuatíni": "Africa/Mbabane",
    "Ilhas Turks e Caicos": "America/Grand_Turk",
    "Chade": "Africa/Ndjamena",
    "Terras Austrais Francesas": "Indian/Kerguelen",
    "Togo": "Africa/Lome",
    "Tailândia": "Asia/Bangkok",
    "Tajiquistão": "Asia/Dushanbe",
    "Toquelau": "Pacific/Fakaofo",
    "Timor-Leste": "Asia/Dili",
    "Turcomenistão": "Asia/Ashgabat",
    "Tunísia": "Africa/Tunis",
    "Tonga": "Pacific/Tongatapu",
    "Turquia": "Europe/Istanbul",
    "Trinidad e Tobago": "America/Port_of_Spain",
    "Tuvalu": "Pacific/Funafuti",
    "Taiwan": "Asia/Taipei",
    "Tanzânia": "Africa/Dar_es_Salaam",
    "Ucrânia": "Europe/Kyiv",
    "Uganda": "Africa/Kampala",
    "Ilhas Menores Distantes dos EUA": "Pacific/Wake",
    "Estados Unidos": "America/New_York",
    "Uruguai": "America/Montevideo",
    "Uzbequistão": "Asia/Tashkent",
    "Vaticano": "Europe/Vatican",
    "São Vicente e Granadinas": "America/St_Vincent",
    "Venezuela": "America/Caracas",
    "Ilhas Virgens Britânicas": "America/Tortola",
    "Ilhas Virgens Americanas": "America/St_Thomas",
    "Vietnã": "Asia/Ho_Chi_Minh",
    "Vanuatu": "Pacific/Efate",
    "Wallis e Futuna": "Pacific/Wallis",
    "Samoa": "Pacific/Apia",
    "Kosovo": "Europe/Belgrade",
    "Iêmen": "Asia/Aden",
    "Mayotte": "Indian/Mayotte",
    "África do Sul": "Africa/Johannesburg",
    "Zâmbia": "Africa/Lusaka",
    "Zimbábue": "Africa/Harare",
}
